namespace: mattermost-preview

stack:
  defines: process-group
  runnable-list:
    - mattermost-preview/mattermost
    - mattermost-preview/nginx
  variables:
    nginx-listen-port:
      type: int
      value: 8080
    mattermost-server-name:
      type: string
      value: "monk-mattermost.com"
    mattermost-image-tag: "latest"
    nginx-image-tag: "latest"