namespace: mattermost-preview

stack:
  defines: process-group
  runnable-list:
    - mattermost-preview/mattermost
    - mattermost-preview/nginx
  variables:
    nginx-listen-port:
      type: int
      value: 80
    mattermost-image-tag: "latest"
    nginx-image-tag: "latest"


