namespace: mattermost-enterprise

stack:
  defines: process-group
  runnable-list:
    - mattermost-enterprise/database
    - mattermost-enterprise/mattermost
    - mattermost-enterprise/nginx
  variables:
    defines: variables
    database-user:
      type: string
      value: "mattermost"
    database-password:
      type: string
      value: "password"
    database-name:
      type: string
      value: "mattermost"
    TZ:
      env: TZ
      type: string
      value: "UTC"
    mattermost-image-tag: 
       type: string
       value: "latest"
    nginx-listen-port:
      type: int
      value: 8080
    nginx-image-tag: 
       type: string
       value: "latest" 